version: '3'

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: always
        ports:
            - "8086:8086" # HTTP API
        env_file:
            - ../.config.env
            - ../env.influxdb
        environment:
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        networks:
            - default
        volumes:
            - influx-data:/var/lib/influxdb
            - ../init_influxdb.iql:/docker-entrypoint-initdb.d/init_influxdb.iql

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        ports:
            - "3000:3000" # HTTP
        env_file:
            - ../env.grafana
            - ../.config.env
        user: "472"
        links:
            - influxdb
        volumes:
            - grafana-data:/var/lib/grafana
            - ../grafana-provisioning:/etc/grafana/provisioning

volumes:
    influx-data:
    grafana-data:

networks:
    default:
        driver: bridge